# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 18:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmark_app', '0002_auto_20161110_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='profile',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
