# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_app', '0003_auto_20161110_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='newrl',
            field=models.URLField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(max_length=60),
        ),
    ]
